### ISSUE TITLE
Make Icons Super Slick

### ISSUE THREAD

**Issue by JugglerX** [stackbithq/jamstackthemes#13]
For the SSG and CMS icons I tried to source the correct logos and use SVG icons where possible. Some are still .png and some of the SVG's don't seem to be well created.

I'd like to get all the icons looking slick.

* Get all the icons in (correctly created) SVG format which can be used in color or black/white.
* Replace any .png icons
* Update any icons which are the incorrect branding (Mkdocs, Pelican?)

Feel free to submit a single icon or many. The current icons are located in `static/images/icons` 

You will also need to update the path to the icon in the relevant markdown file. Ie if you updated the pelican icon you would need to update the `icon` field in `content/ssg/pelican/_index.md`

**Comment by hiverkiya** [comment]
I would like to work on it. Although I'm new, I'll try my best :100:

**Comment by JugglerX** [comment]
Sure have a go. It's kind of a design task. Feel free to do as many icons as you like, you don't need to do them all.

**Comment by hiverkiya** [comment]
Okay sir, I'll make one PR at first to make sure I'm on correct path and then I'll be trying to contribute as much as I can. :) Thanks and have a great day

**Comment by samuelhorn** [comment]
Contributed with the Brunch logo. Will probably fixe more logos later on. #20

**Comment by samuelhorn** [comment]
> @samuelhorn Sir, first of all logo you contributed is awesome. Can you tell me how you create SVG like these as I tried to do and hunt some resources but wasn't able to accomplish any success.
> P.S. No past experience in designing

Thank's. Normally you could find an SVG somewhere online. But often, as with the Brunch logo which is in their header (https://brunch.io/images/logos/brunch-label.svg) there is other stuff like the name. I use sketch as my main tool for editing SVG files. So I download that file, remove the parts not wanted in sketch, clean the lines and flattern shapes and so on. Then save it as a new, square SVG-file. For sketch I also hav a SVG-optimizer plugin which automatically optimizes the SVG-code, removing unnecessary groups and so on.

If there is no SVG-data to be found online you just have to trace it with vectors in a program like Sketch, Adobe Illustrator or something.

This particular issue has really more to do with graphic design rather than coding, even tough SVG consists of code, and it's a pretty big subject. My suggestion is to search for some info on SVG editing online.

**Comment by samuelhorn** [comment]
Made new icons for Hugo, Vuepress, Pelican & 11ty.
I think everything is done here :) #23

**Comment by JugglerX** [comment]
@samuelhorn thanks mate, they look great! I think your right, all our icons are now super slick!
