### ISSUE TITLE
Get the scrub-themes.js script working

### ISSUE THREAD

**Issue by rgroves** [stackbithq/jamstackthemes#42]
The scrub-themes script needs to be rewritten to implement the functionality mentioned in [this comment](https://github.com/stackbithq/jamstackthemes/issues/12#issuecomment-542622677) in #12 and [this comment](https://github.com/stackbithq/jamstackthemes/issues/26#issuecomment-544331428) in #26.

The `scrub-themes.js` script needs to update the theme markdown files in `content/theme/` by:
* Adding or updating a stale flag to the frontmatter for any theme who has not had a recent commit to it's specified branch
* Adding the github_branch setting with the repo's default branch name, only when no branch is explicitly specified in the frontmatter already.

This process should be driven by the theme data stored in `data/themes.json` (which is generated by the `generate-github.js` script). Each theme object stored within the themes.json has the appropriate `last_commit` and `branch` that should be used in implementing the above requirements.

**Comment by rgroves** [comment]
I'm currently working on this so I can then move #26 forward.

@JugglerX  What do you want the cutoff date for determining the "stale" status? A hardcoded date of January 1st, 2018 is being used. It should likely be based on a calculation from the current date. Is something like current date minus one year acceptable (so a repo without a commit in the past year would be considered stale)? Or should the period be shorter than a year?

**Comment by JugglerX** [comment]
@rgroves thanks for the PR with the scrub script. I did some work today which generates the github_branch and last_commit data in the `generate-github.js` - So this is available in `data/themes.json`

I was able to run `scrub-themes.js` and add the github_branch to the markdown files, which is nice. I also used it to generate a submission date for each theme. If we are going to be modifying the markdown files programmatically we need to decouple from using git info as the themes "submission date"

I tested the scrub script to generate stale data and it does, great! But I think this data should live in the `data/themes.json` not in the markdown. Let me know if you want to do that otherwise I can make the changes.

Really appreciate your work on this, thanks! :)

**Comment by rgroves** [comment]
Sorry, I misunderstood where the stale flag should reside. I can work on moving this into `data/themes.json` via the `generate-github.js` script.

**Comment by JugglerX** [comment]
Ok sure. I agree it should exist in `generate-github.js`. `stale` flag is something we can update every build. 

Broadly speaking. We want to avoid modifying the markdown files as much as possible. The scrub script should be used to make major updates to the markdown files when otherwise unavoidable.

**Comment by rgroves** [comment]
That makes sense. Will have a PR for this later today.
